### ISSUE TITLE
Tidehollow Sculler doesn't return exiled card

### ISSUE THREAD

**Issue by Statsme** [magefree/mage#744]
Hi

Just noticed that when Tidehollow leaves the battlefield, its trigger appears but does not return the card to my opponent's hand.

Just checking that this is a known issue as it's one of my favourite cards!

Thanks

**Comment by LevelX2** [comment]
Already fixed with this commit.
https://github.com/magefree/mage/commit/d8e1a843c6abaae8678e35a46699852f939ad0df

**Comment by Statsme** [comment]
Hi there

Thanks for the amazingly fast response. Haven't played for a week but came back today and my Tidehollow was bounced by a cryptic command and my opponent didn't get his card back.

When you say "fixed with this commit", does this mean it'll be fixed in the next version rather than right  now? Or is it not completely fixed? Just trying to make the program even better!

Cheers

**Comment by emerald000** [comment]
It means that it is fixed in the development version and will be released in the next update.

**Comment by Statsme** [comment]
I see. Thanks for the clarification.
